/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2019-01-29 07:49:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class show_005fmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"Viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>在线点餐系统</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".input-group {\r\n");
      out.write("\tmargin-top: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_item {\r\n");
      out.write("\twidth: 130px;\r\n");
      out.write("\theight: 175px;\r\n");
      out.write("\tborder: 1px solid #ededed;\r\n");
      out.write("\tdisplay: inline-flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\tmargin: 5px;\r\n");
      out.write("\tpadding-top: 3px;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_item_ed {\r\n");
      out.write("\twidth: 130px;\r\n");
      out.write("\theight: 175px;\r\n");
      out.write("\tborder: 1px solid #ededed;\r\n");
      out.write("\tdisplay: inline-flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\tmargin: 5px;\r\n");
      out.write("\tpadding-top: 3px;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_item img {\r\n");
      out.write("\twidth: 110px;\r\n");
      out.write("\theight: 110px;\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_item_ed img {\r\n");
      out.write("\twidth: 110px;\r\n");
      out.write("\theight: 110px;\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_item span {\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_item_ed span {\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_item button {\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_item_ed button {\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".confirm_div {\r\n");
      out.write("\tmargin: 5px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\tjustify-content: space-around;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sum {\r\n");
      out.write("\tfont-family: monospace;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".name_div {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: row;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_div {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: row;\r\n");
      out.write("\tjustify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".add {\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".a {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tborder: 1px solid #ededed;\r\n");
      out.write("\tdisplay: inline-flex;\r\n");
      out.write("\tflex-wrap: wrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".b {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tborder: 1px solid #ededed;\r\n");
      out.write("\tdisplay: inline-flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\">请选择你的菜式</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- <form class=\"bs-example bs-example-form\" role=\"form\" action=\"\"\r\n");
      out.write("\t\t\t\tmethod=\"post\"> -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"搜索菜式\"\r\n");
      out.write("\t\t\t\t\t\tid=\"text\" name=\"food_name\" /> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\tname=\"order_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\tname=\"table_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${table_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"search('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${table_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\">Go!</button>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- </form> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"#\">选择菜谱</a></li>\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li onclick=\"person_info('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${table_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\"><a>个人中心</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 菜谱部分 -->\r\n");
      out.write("\t\t\t<div class=\"col-sm-8 a\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 已选菜单部分 -->\r\n");
      out.write("\t\t\t<div class=\"col-sm-2 b\" id=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t<div class=\"confirm_div\">\r\n");
      out.write("\t\t\t\t\t<!-- <form action=\"\"> -->\r\n");
      out.write("\t\t\t\t\t<button onclick=\"getMenuList('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${table_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\">提交订单</button>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text\">总价：￥</span><span class=\"sum\" id=\"sum\"> ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 总价：<span class=\"count\" name=\"count\">0</span> -->\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- </form> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction person_info(order_id, table_id) {\r\n");
      out.write("\t\t\tvar sum = document.getElementById(\"sum\").innerHTML;\r\n");
      out.write("\t\t\tvar menuListed = getListed();\r\n");
      out.write("\t\t\tvar params = {\r\n");
      out.write("\t\t\t\t\"order_id\" : order_id,\r\n");
      out.write("\t\t\t\t\"table_id\" : table_id,\r\n");
      out.write("\t\t\t\t\"sum\" : sum,\r\n");
      out.write("\t\t\t\t\"menuListed\" : menuListed\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\thttpPost(\"person_info\", params);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction httpPost(URL, PARAMS) {\r\n");
      out.write("\t\t\tvar temp = document.createElement(\"form\");\r\n");
      out.write("\t\t\ttemp.action = URL;\r\n");
      out.write("\t\t\ttemp.method = \"post\";\r\n");
      out.write("\t\t\ttemp.style.display = \"none\";\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor ( var x in PARAMS) {\r\n");
      out.write("\t\t\t\tvar opt = document.createElement(\"textarea\");\r\n");
      out.write("\t\t\t\topt.name = x;\r\n");
      out.write("\t\t\t\topt.value = PARAMS[x];\r\n");
      out.write("\t\t\t\ttemp.appendChild(opt);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.body.appendChild(temp);\r\n");
      out.write("\t\t\ttemp.submit();\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn temp;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction search(order_id, table_id) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar text = document.getElementById(\"text\").value;\r\n");
      out.write("\t\t\tvar menuListed = getListed();\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar sum = document.getElementById(\"sum\").innerHTML;\r\n");
      out.write("\r\n");
      out.write("\t\t\t/* window.location.href = \"search?food1=\" + text + \"&order_id=\"\r\n");
      out.write("\t\t\t\t\t+ order_id + \"&table_id=\" + table_id + \"&menuListed=\"\r\n");
      out.write("\t\t\t\t\t+ menuListed;\r\n");
      out.write("\t\t\t */\r\n");
      out.write("\t\t\tvar params = {\r\n");
      out.write("\t\t\t\t\"food1\" : text,\r\n");
      out.write("\t\t\t\t\"order_id\" : order_id,\r\n");
      out.write("\t\t\t\t\"table_id\" : table_id,\r\n");
      out.write("\t\t\t\t\"sum\" : sum,\r\n");
      out.write("\t\t\t\t\"menuListed\" : menuListed\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\thttpPost(\"search\", params);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction selectFood(menuId1, menuName1, menuPrice1, menuImg1) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t/* 如果所选菜式已在已选菜单列表中，则直接数量加1 */\r\n");
      out.write("\t\t\tvar selectMenuItem = document.getElementById(menuId1);\r\n");
      out.write("\t\t\tif (selectMenuItem != null) {\r\n");
      out.write("\t\t\t\tupdateCount(selectMenuItem, true);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t/* 如果不在已选菜单列表中，则创建菜单 */\r\n");
      out.write("\t\t\t\tselectMenuItem = document.createElement(\"div\");\r\n");
      out.write("\t\t\t\tselectMenuItem.setAttribute(\"class\", \"menu_item_ed\");\r\n");
      out.write("\t\t\t\tselectMenuItem.setAttribute(\"id\", menuId1);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t/* 菜单图片 */\r\n");
      out.write("\t\t\t\tvar menuImg = document.createElement(\"img\");\r\n");
      out.write("\t\t\t\tmenuImg.setAttribute(\"class\", \"menu_img_ed\");\r\n");
      out.write("\t\t\t\tmenuImg.setAttribute(\"src\", menuImg1);\r\n");
      out.write("\t\t\t\tselectMenuItem.appendChild(menuImg);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar nameDiv = document.createElement(\"div\");\r\n");
      out.write("\t\t\t\tnameDiv.setAttribute(\"class\", \"name_div\");\r\n");
      out.write("\t\t\t\tselectMenuItem.appendChild(nameDiv);\r\n");
      out.write("\t\t\t\t/* 菜单名称 */\r\n");
      out.write("\t\t\t\tvar menuName = document.createElement(\"span\");\r\n");
      out.write("\t\t\t\tmenuName.setAttribute(\"class\", \"menu_name_ed\");\r\n");
      out.write("\t\t\t\tmenuName.innerHTML = menuName1 + \" x \";\r\n");
      out.write("\t\t\t\tnameDiv.appendChild(menuName);\r\n");
      out.write("\t\t\t\t/* 菜单数量 */\r\n");
      out.write("\t\t\t\tvar menuCount = document.createElement(\"span\");\r\n");
      out.write("\t\t\t\tmenuCount.setAttribute(\"class\", \"menu_count_ed\");\r\n");
      out.write("\t\t\t\tmenuCount.innerHTML = 1;\r\n");
      out.write("\t\t\t\tnameDiv.appendChild(menuCount);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t/* 菜单价格 */\r\n");
      out.write("\t\t\t\tvar menuPrice = document.createElement(\"span\");\r\n");
      out.write("\t\t\t\tmenuPrice.setAttribute(\"class\", \"menu_price_ed\");\r\n");
      out.write("\t\t\t\tmenuPrice.innerHTML = menuPrice1;\r\n");
      out.write("\t\t\t\tselectMenuItem.appendChild(menuPrice);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar btnDiv = document.createElement(\"div\");\r\n");
      out.write("\t\t\t\tbtnDiv.setAttribute(\"class\", \"btn_div\");\r\n");
      out.write("\t\t\t\tselectMenuItem.appendChild(btnDiv);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t/*增加  */\r\n");
      out.write("\t\t\t\tvar addBtn = document.createElement(\"button\");\r\n");
      out.write("\t\t\t\taddBtn.setAttribute(\"class\", \"add\");\r\n");
      out.write("\t\t\t\taddBtn.setAttribute(\"onclick\", \"onAdd(\" + menuPrice1 + \",\"\r\n");
      out.write("\t\t\t\t\t\t+ menuId1 + \")\");\r\n");
      out.write("\t\t\t\taddBtn.innerHTML = \"+\";\r\n");
      out.write("\t\t\t\tbtnDiv.appendChild(addBtn);\r\n");
      out.write("\t\t\t\t/*减少  */\r\n");
      out.write("\t\t\t\tvar minusBtn = document.createElement(\"button\");\r\n");
      out.write("\t\t\t\tminusBtn.setAttribute(\"class\", \"minus\");\r\n");
      out.write("\t\t\t\tminusBtn.setAttribute(\"onclick\", \"onMinus(\" + menuPrice1 + \",\"\r\n");
      out.write("\t\t\t\t\t\t+ menuId1 + \")\");\r\n");
      out.write("\t\t\t\tminusBtn.innerHTML = \"-\";\r\n");
      out.write("\t\t\t\tbtnDiv.appendChild(minusBtn);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar bodyFa = document.getElementById(\"col-sm-2\");\r\n");
      out.write("\t\t\t\tbodyFa.appendChild(selectMenuItem);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tupdatePrice(menuPrice1, true);\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction updateCount(selectMenuItem, isAdd) {\r\n");
      out.write("\t\t\tvar menuCount = selectMenuItem.getElementsByTagName(\"span\")[1];\r\n");
      out.write("\t\t\tvar count = parseInt(menuCount.innerHTML);\r\n");
      out.write("\t\t\tif (isAdd) {\r\n");
      out.write("\t\t\t\tcount++;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tcount--;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (count == 0) {\r\n");
      out.write("\t\t\t\tvar node = selectMenuItem.parentNode;\r\n");
      out.write("\t\t\t\tnode.removeChild(selectMenuItem);\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tmenuCount.innerHTML = count;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction updatePrice(menuPrice1, isAdd) {\r\n");
      out.write("\t\t\t/* 更新总价 */\r\n");
      out.write("\t\t\tvar countSpan = document.getElementsByClassName(\"sum\");\r\n");
      out.write("\t\t\tvar count = parseFloat(countSpan[0].innerHTML);\r\n");
      out.write("\t\t\t//var count = parseFloat(countSpan[0].value);\r\n");
      out.write("\t\t\tif (isAdd) {\r\n");
      out.write("\t\t\t\tcount += parseFloat(menuPrice1);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tcount -= parseFloat(menuPrice1);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tcountSpan[0].innerHTML = Math.round(count * 100) / 100;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/* 增加按钮 */\r\n");
      out.write("\t\tfunction onAdd(menuPrice, menuId) {\r\n");
      out.write("\t\t\tvar selectMenuItem = document.getElementById(menuId);\r\n");
      out.write("\t\t\tupdateCount(selectMenuItem, true);\r\n");
      out.write("\t\t\tupdatePrice(menuPrice, true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction onMinus(menuPrice, menuId) {\r\n");
      out.write("\t\t\tvar selectMenuItem = document.getElementById(menuId);\r\n");
      out.write("\t\t\tupdateCount(selectMenuItem, false);\r\n");
      out.write("\t\t\tupdatePrice(menuPrice, false);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction getMenuList(order_id, table_id) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar menuList = getList();\r\n");
      out.write("\t\t\tvar countSpan = document.getElementsByClassName(\"sum\");\r\n");
      out.write("\t\t\tvar count = parseFloat(countSpan[0].innerHTML);\r\n");
      out.write("\t\t\tif (count == 0) {\r\n");
      out.write("\t\t\t\twindow.alert(\"请选择您的菜式\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\twindow.location.href = \"submit_form?order_id=\" + order_id\r\n");
      out.write("\t\t\t\t\t\t+ \"&table_id=\" + table_id + \"&sum=\" + count\r\n");
      out.write("\t\t\t\t\t\t+ \"&food_list=\" + menuList;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction getList() {\r\n");
      out.write("\t\t\tvar divList = document.getElementsByClassName(\"menu_item_ed\");\r\n");
      out.write("\t\t\tvar amountList = document.getElementsByClassName(\"menu_count_ed\");\r\n");
      out.write("\t\t\tvar menuList = new Array();\r\n");
      out.write("\t\t\tfor (var i = 0; i < divList.length; i++) {\r\n");
      out.write("\t\t\t\tvar menuId = divList[i].id;\r\n");
      out.write("\t\t\t\tvar menuAmount = amountList[i].innerHTML;\r\n");
      out.write("\t\t\t\tvar item = [ menuId, menuAmount ];\r\n");
      out.write("\t\t\t\tmenuList[i] = item;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn menuList;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction getListed() {\r\n");
      out.write("\t\t\tvar divList = document.getElementsByClassName(\"menu_item_ed\");\r\n");
      out.write("\t\t\tvar amountList = document.getElementsByClassName(\"menu_count_ed\");\r\n");
      out.write("\t\t\tvar nameList = document.getElementsByClassName(\"menu_name_ed\");\r\n");
      out.write("\t\t\tvar imgList = document.getElementsByClassName(\"menu_img_ed\");\r\n");
      out.write("\t\t\tvar priceList = document.getElementsByClassName(\"menu_price_ed\");\r\n");
      out.write("\t\t\tvar menuList = new Array();\r\n");
      out.write("\t\t\tfor (var i = 0; i < divList.length; i++) {\r\n");
      out.write("\t\t\t\t//id\r\n");
      out.write("\t\t\t\tvar menuId = divList[i].id;\r\n");
      out.write("\t\t\t\t//name\r\n");
      out.write("\t\t\t\tvar menuName = nameList[i].innerHTML;\r\n");
      out.write("\t\t\t\t//img\r\n");
      out.write("\t\t\t\tvar menuImg = imgList[i].src;\r\n");
      out.write("\t\t\t\t//price\r\n");
      out.write("\t\t\t\tvar menuPrice = priceList[i].innerHTML;\r\n");
      out.write("\t\t\t\t//amout\r\n");
      out.write("\t\t\t\tvar menuAmount = amountList[i].innerHTML;\r\n");
      out.write("\t\t\t\tvar item = [ menuId, menuName, menuPrice, menuImg, menuAmount ];\r\n");
      out.write("\t\t\t\tmenuList[i] = item;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn menuList;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /show_menu.jsp(167,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /show_menu.jsp(167,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("menu");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class=\"menu_item\">\r\n");
          out.write("\t\t\t\t\t\t<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" /> <span class=\"menu_name\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t<span class=\"menu_price\">￥:");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t<button class=\"menu_confirm\"\r\n");
          out.write("\t\t\t\t\t\t\tonclick=\"selectFood('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\">点菜</button>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /show_menu.jsp(183,64) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sum  == NULL}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('0');
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /show_menu.jsp(184,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sum  != NULL}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /show_menu.jsp(192,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuListed}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /show_menu.jsp(192,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("menu");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class=\"menu_item_ed\" id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t<img class=\"menu_img_ed\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_img }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" />\r\n");
          out.write("\t\t\t\t\t\t<div class=\"name_div\">\r\n");
          out.write("\t\t\t\t\t\t\t<span class=\"menu_name_ed\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("x</span> <span\r\n");
          out.write("\t\t\t\t\t\t\t\tclass=\"menu_count_ed\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_amount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<span class=\"menu_price_ed\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"btn_div\">\r\n");
          out.write("\t\t\t\t\t\t\t<button class=\"add\"\r\n");
          out.write("\t\t\t\t\t\t\t\tonclick=\"onAdd('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\">+</button>\r\n");
          out.write("\t\t\t\t\t\t\t<button class=\"minus\"\r\n");
          out.write("\t\t\t\t\t\t\t\tonclick=\"onMinus('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('\'');
          out.write(',');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.food_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\">-</button>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
